// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'hide-MSPabionbDGSQoGL7K1oh_qD07in4',
    appId: '1:688124174143:web:96a2f635027666c3e13d8a',
    messagingSenderId: '688124174143',
    projectId: 'moneybuddy-78b57',
    authDomain: 'moneybuddy-78b57.firebaseapp.com',
    databaseURL: 'https://moneybuddy-78b57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moneybuddy-78b57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'hide',
    appId: '1:688124174143:android:f1ba9618fbc67d7de13d8a',
    messagingSenderId: '688124174143',
    projectId: 'moneybuddy-78b57',
    databaseURL: 'https://moneybuddy-78b57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moneybuddy-78b57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'hide_6EjG3mmeWTYHfZsDhq4gSQ',
    appId: '1:688124174143:ios:050d689cf341ed6de13d8a',
    messagingSenderId: '688124174143',
    projectId: 'moneybuddy-78b57',
    databaseURL: 'https://moneybuddy-78b57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moneybuddy-78b57.appspot.com',
    iosBundleId: 'com.example.flutterFirstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'hide_6EjG3mmeWTYHfZsDhq4gSQ',
    appId: '1:688124174143:ios:050d689cf341ed6de13d8a',
    messagingSenderId: '688124174143',
    projectId: 'moneybuddy-78b57',
    databaseURL: 'https://moneybuddy-78b57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moneybuddy-78b57.appspot.com',
    iosBundleId: 'com.example.flutterFirstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'hide-MSPabionbDGSQoGL7K1oh_qD07in4',
    appId: '1:688124174143:web:0d76061ef21afd6ce13d8a',
    messagingSenderId: '688124174143',
    projectId: 'moneybuddy-78b57',
    authDomain: 'moneybuddy-78b57.firebaseapp.com',
    databaseURL: 'https://moneybuddy-78b57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moneybuddy-78b57.appspot.com',
  );
}
